version: "3.8"

services:
  pod-api-dev:
    build:
      context: ./pod_automation_api
      dockerfile: Dockerfile.dev
    container_name: pod-api-dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - ./:/app  # Mount the entire project directory at /app
    networks:
      - pod_network_dev
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/pod_automation:/pod_automation_api  # Set PYTHONPATH to include all necessary directories
    env_file:
      - .env.dev
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    # Added healthcheck to verify API is running correctly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  pod-frontend-dev:
    build:
      context: ./pod_automation_frontend
      dockerfile: Dockerfile.dev
    container_name: pod-frontend-dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./pod_automation_frontend:/app
      - /app/node_modules
    networks:
      - pod_network_dev
    environment:
      - VITE_API_URL=http://localhost:8001/api/v1
    command: npm run dev -- --host 0.0.0.0

networks:
  pod_network_dev:
    driver: bridge
