openapi: 3.1.0
info:
  title: POD AI Automation API
  description: |
    API for Etsy POD sellers automation platform. This API provides endpoints for authentication,
    SEO optimization, AI design generation, mockup creation, and Etsy integration.
  version: 1.0.0
  contact:
    name: POD AI Automation Support
    email: support@podaiautomation.com
servers:
  - url: /api/v1
    description: Production server
  - url: http://localhost:8000/api/v1
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        avatar_url:
          type: string
          format: uri
        created_at:
          type: string
          format: date-time
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    SignupRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        name:
          type: string
    AuthResponse:
      type: object
      required:
        - access_token
        - refresh_token
        - user
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        user:
          $ref: '#/components/schemas/User'
    RefreshRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
    EtsyListing:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        price:
          type: number
          format: float
        status:
          type: string
          enum: [active, draft, inactive]
        thumbnail_url:
          type: string
          format: uri
        seo_score:
          type: integer
          minimum: 0
          maximum: 100
    ListingOptimizationRequest:
      type: object
      required:
        - listing_id
      properties:
        listing_id:
          type: string
        current_title:
          type: string
        current_tags:
          type: array
          items:
            type: string
        current_description:
          type: string
    ListingOptimizationResponse:
      type: object
      properties:
        optimized_title:
          type: string
        optimized_tags:
          type: array
          items:
            type: string
        optimized_description:
          type: string
        seo_score:
          type: integer
          minimum: 0
          maximum: 100
        recommendations:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
                enum: [title, tags, description]
              score:
                type: integer
              feedback:
                type: string
    SubscriptionPlan:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        interval:
          type: string
          enum: [month, year]
        features:
          type: array
          items:
            type: string
    SubscriptionResponse:
      type: object
      required:
        - id
        - status
        - plan
      properties:
        id:
          type: string
        status:
          type: string
          enum: [active, canceled, past_due, trialing]
        plan:
          $ref: '#/components/schemas/SubscriptionPlan'
        current_period_end:
          type: string
          format: date-time
        cancel_at_period_end:
          type: boolean
paths:
  /auth/login:
    post:
      summary: Login with email and password
      operationId: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/signup:
    post:
      summary: Create a new user account
      operationId: signup
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    post:
      summary: Refresh access token
      operationId: refreshToken
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /etsy/test-listings:
    get:
      summary: Get test Etsy listings (no auth required)
      operationId: getEtsyListings
      tags:
        - etsy
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, draft, inactive, all]
          description: Filter listings by status
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of items per page
      responses:
        '200':
          description: List of Etsy listings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/EtsyListing'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      pages:
                        type: integer
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /etsy/listings:
    get:
      summary: Get user's Etsy listings
      operationId: getAuthenticatedEtsyListings
      tags:
        - etsy
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, draft, inactive, all]
          description: Filter listings by status
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of items per page
      responses:
        '200':
          description: List of Etsy listings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/EtsyListing'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      pages:
                        type: integer
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /seo/optimize-listing:
    post:
      summary: Optimize an Etsy listing's SEO
      operationId: optimizeListing
      tags:
        - seo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListingOptimizationRequest'
      responses:
        '200':
          description: Optimized listing data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingOptimizationResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Listing not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
